(function(root){
    let Scenes = root.Main.Scenes,
        Scene_Map = root.Scene_Map;

    Scenes.set("intro",new Scene_Map({
        map:{
            loop_x:false,
            loop_y:false,
            tilesets:[
                {
                    graphicID:"forest2",
                    cols:8,
                    rows:149,
                    width:256,
                    height:4768
                },
                {
                    graphicID:"cavesAndUnderground",
                    cols:8,
                    rows:17,
                    width:256,
                    height:544
                }
            ],
            spriteset:{
                width:100,
                height:100,
                tileWidth:32,
                tileHeight:32,
                data:[]
            }
        },
        objects:[
            {
                class:"Event",
                x:300,
                y:300,
                width:30,
                height:30,
                static:true,
                charaID:"darkness",
                animationSpeed:10,
                pages:[
                    {
                        through:true,
                        touch:function(obj){

                        }
                    }
                ]
            },
            {
                class:"Event",
                x:500,
                y:300,
                width:30,
                height:64,
                static:true,
                charaID:"cristal",
                animationSpeed:2,
                pages:[
                    {
                        through:false,
                        touch:function(obj){

                        }
                    }
                ]
            }
        ]
    }));

    Scenes.set("map02",new Scene_Map({
        map:{
            loop_x:false,
            loop_y:false,
            tilesets:[
                {
                    graphicID:"forest2",
                    cols:8,
                    rows:149,
                    width:256,
                    height:4768
                },
                {
                    graphicID:"cavesAndUnderground",
                    cols:8,
                    rows:17,
                    width:256,
                    height:544
                }
            ],
            spriteset:{
                width:20,
                height:20,
                tileWidth:32,
                tileHeight:32,
                data:[]
            }
        }
    }));
})(RPG);